services:
  db-POSTGRES:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres-db:/var/lib/postgresql/
  db-MYSQL:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: 'mysql'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'passwordnotroot'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '%'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  mysql-db:
  postgres-db:
