#sparkJobNamespace: spark-apps #"observa somente os jobs enviados para o namespace 'spark'"
serviceAccounts:
  sparkoperator:
    # -- Create a service account for the operator
    create: true
    # -- Optional name for the operator service account
    #name: ""
  spark:
    # -- Create a service account for spark apps
    create: true
    # -- Optional name for the spark service account
    name: "spark-on-k8s-operator-spark"

webhook:
  # -- Enable webhook server
  enable: true
  # # -- The webhook server will only operate on namespaces with this label, specified in the form key1=value1,key2=value2.
  # # Empty string (default) will operate on all namespaces
  # namespaceSelector: "spark"
